name: sync blog entries

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name to run this workflow'
        required: false
        type: 'string'
        default: 'master'

permissions:
  contents: 'write'
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
    - name: show github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo ${GITHUB_CONTEXT}
